#!/usr/bin/make

#defaults
LIB = foreseer

#main building variables
DOBJ    = static/obj/
DMOD    = static/mod/
DEXE    = static/
MAKELIB = ar -rcs $(DEXE)lib$(LIB).a $(DOBJ)*.o ; ranlib $(DEXE)lib$(LIB).a
DSRC    = src
FC      = gfortran
OPTSC   = -cpp -c -frealloc-lhs -O3 -J static/mod
OPTSL   = -J static/mod
VPATH   = $(DSRC) $(DOBJ) $(DMOD)
MKDIRS  = $(DOBJ) $(DMOD) $(DEXE)

#auxiliary variables
COTEXT  = "Compiling $(<F)"
LITEXT  = "Assembling $@"

#building rule
$(LIB): $(MKDIRS) $(DOBJ)$(LIB).o
	@echo $(LITEXT)
	@$(MAKELIB)

#compiling rules
$(DOBJ)foreseer_riemann_solver_compressible_exact.o: src/FORESEER/foreseer_riemann_solver_compressible_exact.F90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_compressible_pvl.o \
	$(DOBJ)foreseer_riemann_solver_object.o \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_solver_compressible_llf.o: src/FORESEER/foreseer_riemann_solver_compressible_llf.F90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_compressible_pvl.o \
	$(DOBJ)foreseer_riemann_solver_object.o \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_solver_compressible_pvl.o: src/FORESEER/foreseer_riemann_solver_compressible_pvl.f90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_compressible_pvl.o \
	$(DOBJ)foreseer_riemann_solver_object.o \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_solver_compressible_roe.o: src/FORESEER/foreseer_riemann_solver_compressible_roe.F90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_compressible_pvl.o \
	$(DOBJ)foreseer_riemann_pattern_compressible_roe.o \
	$(DOBJ)foreseer_riemann_solver_object.o \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_pattern_compressible_pvl.o: src/FORESEER/foreseer_riemann_pattern_compressible_pvl.f90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_compressible_object.o \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_solver_object.o: src/FORESEER/foreseer_riemann_solver_object.f90 \
	$(DEXE)libflow.a \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_pattern_compressible_object.o: src/FORESEER/foreseer_riemann_pattern_compressible_object.f90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_object.o \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_pattern_compressible_roe.o: src/FORESEER/foreseer_riemann_pattern_compressible_roe.f90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_compressible_object.o \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_solver_compressible_hllc.o: src/FORESEER/foreseer_riemann_solver_compressible_hllc.F90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_compressible_pvl.o \
	$(DOBJ)foreseer_riemann_solver_object.o \
	$(DEXE)libpenf.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer.o: src/FORESEER/foreseer.f90 \
	$(DEXE)libflow.a \
	$(DOBJ)foreseer_riemann_pattern_compressible_object.o \
	$(DOBJ)foreseer_riemann_pattern_compressible_pvl.o \
	$(DOBJ)foreseer_riemann_pattern_object.o \
	$(DOBJ)foreseer_riemann_solver_compressible_exact.o \
	$(DOBJ)foreseer_riemann_solver_compressible_hllc.o \
	$(DOBJ)foreseer_riemann_solver_compressible_llf.o \
	$(DOBJ)foreseer_riemann_solver_compressible_pvl.o \
	$(DOBJ)foreseer_riemann_solver_compressible_roe.o \
	$(DOBJ)foreseer_riemann_solver_object.o
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

$(DOBJ)foreseer_riemann_pattern_object.o: src/FORESEER/foreseer_riemann_pattern_object.f90 \
	$(DEXE)libflow.a \
	$(DEXE)libvecfor.a
	@echo $(COTEXT)
	@$(FC) $(OPTSC) $< -o $@

.NOTPARALLEL: $(DEXE)libflow.a $(DEXE)libpenf.a $(DEXE)libvecfor.a

$(DEXE)libflow.a:
	@$(MAKE) -f makefile.flow

$(DEXE)libpenf.a:
	@$(MAKE) -f makefile.penf

$(DEXE)libvecfor.a:
	@$(MAKE) -f makefile.vecfor

#phony auxiliary rules
.PHONY : $(MKDIRS)
$(MKDIRS):
	@mkdir -p $@
.PHONY : cleanobj
cleanobj:
	@echo deleting objects
	@rm -fr $(DOBJ)
.PHONY : cleanmod
cleanmod:
	@echo deleting mods
	@rm -fr $(DMOD)
.PHONY : clean
clean: cleanobj cleanmod
